### ISSUE TITLE
뉴스 결과를 전달하는 방식에 대하여

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#1]
뉴스 결과를 전달할 때 텍스트 형식 말고
카드텍스트 형식으로 하는건 어떤가요?

그게 한눈에 보기 좋을것같은데
텍스트로만 전달하다보니 채팅봇을 사용하는 사용자 관점에서는
답변이 너무 지저분한 형태로 전달됩니다.
![11](https://user-images.githubusercontent.com/76954598/118754539-42cee480-b8a2-11eb-90a0-b85de833fba8.png)

**Comment by DaeguKIng** [comment]
카카오 i 오픈 빌더의 Card.list 형태의 출력을 고려해보겠습니다. 감사합니다.

**Comment by B-G-Y** [comment]
네 감사합니다. :D

**Comment by DaeguKIng** [comment]
Feature/KDY에 news_cardList.py로 수정본 새 파일로 업로딩 하였습니다.

**Comment by karist123** [comment]
![image](https://user-images.githubusercontent.com/83295412/118774705-14143680-b8c1-11eb-8a3e-d04b850108fb.png)

환율 정보만 나오고 더 자세한 정보와 그래프 사진이 있으면 좋을것 같습니다.

**Comment by B-G-Y** [comment]
네 감사합니다.
