### ISSUE TITLE
'음악 서비스'에 대하여

### ISSUE THREAD

**Issue by karist123** [B-G-Y/Team_Project_OPSW#10]
825dbb0935833f92215a9dad119274032a72894e

![image](https://user-images.githubusercontent.com/83295412/119101408-eca1a300-ba53-11eb-9b12-7e069af92b30.png)
음악 서비스를 이용 할려고 하였는데 작동이 되지않습니다.
확인하여 수정바랍니다.

**Comment by B-G-Y** [comment]
수정해서 올리겠습니다.

**Comment by B-G-Y** [comment]
1c9ae46209d9d3dad100cd27334726f53688ace6

확인 부탁드립니다.

**Comment by karist123** [comment]
확인했습니다.
감사합니다.
