### ISSUE TITLE
카드리스트  형식에 대하여

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#3]
66175aa375cfd979dfeb0a0b30e55ef38dde3dbe

의 파이썬 파일을 바탕으로
카카오톡 봇을 운영할 경우 

다음과 같은 문제가 생깁니다.
![22](https://user-images.githubusercontent.com/76954598/118779325-e4b3f880-b8c5-11eb-8e26-91a5e7d4fcf9.png)

카드리스트형식인
타이틀 
list내용
list내용
list내용

가 아닌

타이틀(list내용)
litt내용
list내용

입니다

이에 대해서 해결해 주시면 감사합니다.

**Comment by DaeguKIng** [comment]
지적 감사합니다. 빠른 시일 내 수정 후 push 해두겠습니다.

**Comment by DaeguKIng** [comment]
Feature/KDY에 해당 사항 수정본 push 하였습니다.

**Comment by B-G-Y** [comment]
네 확인했습니다 정상적으로 작동합니다.

![33](https://user-images.githubusercontent.com/76954598/118812814-7e40d180-b8e9-11eb-8175-d8307b46cf50.png)

감사합니다 :D
