### ISSUE TITLE
Exchange_rate.py에 대하여 누락된 부분이 있습니다.

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#4]
a300017befd4de145f68cfd873610314b4d3b9cd

![image](https://user-images.githubusercontent.com/76954598/118795797-eeddf300-b8d5-11eb-9649-065906b4aade.png)
에 추가된 파일을 보면 return jsonify(res)까지만 나와있기에

메인함수를 추가해줘야 실행이 가능합니다.
![image](https://user-images.githubusercontent.com/76954598/118796143-48462200-b8d6-11eb-9246-1f6a5657051d.png)

를 넣은 파일로 수정바랍니다.

**Comment by karist123** [comment]
죄송합니다 수정하여 올렸습니다.

**Comment by B-G-Y** [comment]
확인했습니다.
