### ISSUE TITLE
Exchange_rate.py에 대하여

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#5]
06d75ec9583a4972359826edf6cd47e5895128cb

로 수정한 Exchange_rate.py를 실행할경우 

정상적으로  작동하지만 아쉬운 점이 있습니다.

단순히 환전 비율인 내용의 text만 전달하는게 아닌,

시각자료도 있으면 좋다고 생각합니다.

예를 들어, 시간에 따라 환율어 어떻게 변했는지
 
text형식이 아닌 Card.image형식으로 그래프 이미지를 삽입하여 같이 보여주는겁니다.

이렇게 한다면 보다 더 좋은 기능이 제공되는 enhancement가 될거라 생각합니다.

이 의견에 대해서 어떻게 생각하시는지 궁금합니다.

**Comment by karist123** [comment]
환율 그래프의 시각적 자료와 더보기 버튼을 추가하여
좀 더 환율에 관한 자세한 정보를 얻을 수 있도록 수정하였습니다.

**Comment by B-G-Y** [comment]
네 확인했습니다.
