### ISSUE TITLE
covid_cardList.py에 대하여

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#6]
dc54777a5390b8dd24d8b94e6c4ad23a5ac06d4e

의 77번째줄과 78번째줄을 보면 서로 안맞습니다. 

수정바랍니다.

![image](https://user-images.githubusercontent.com/76954598/118845657-f073df00-b906-11eb-8ee7-470dbd6e1701.png)

**Comment by DaeguKIng** [comment]
즉시 수정 후 재업로딩 하겠습니다. 감사합니다.

**Comment by B-G-Y** [comment]
네 확인했습니다.
