### ISSUE TITLE
Exchange_rate.py 문제점 발생

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#7]
b3d1f9846a4d0d27b3ebf73339023616074f614c

의 Exchange_rate.py를 기반으로 실행할경우

다음과 같은 문제점이 있습니다.

![44](https://user-images.githubusercontent.com/76954598/118965446-a987f700-b9a3-11eb-8829-4f3fba6a4f93.png)

환율의 정보를 주는 텍스트는 정상적으로 출력이 되었지만,

위의 사진처럼 국가별 환율그래프 이미지가 동일하게 설정되어있습니다.

이에 대하여 fix해주셨으면 합니다.

**Comment by karist123** [comment]
확인 했습니다. 수정 후 올리겠습니다.

**Comment by karist123** [comment]
국가별 환율그래프 수정 및 버그를 수정하여서 올렸습니다.

**Comment by B-G-Y** [comment]
네 확인했습니다 잘 실행됩니다. 

![55](https://user-images.githubusercontent.com/76954598/118974230-8a8e6280-b9ad-11eb-93d7-9c0237d2bf35.png)
