### ISSUE TITLE
'음악 서비스'에 대한 의견

### ISSUE THREAD

**Issue by DaeguKIng** [B-G-Y/Team_Project_OPSW#8]
5bbad6da7cd4a4ec3a6cf340330f3480e84b6787
기존 일간 인치차트 외 주간 및 실시간 인기차트에 대한 정보도 제공된다면 좀 더 실용적일 것 같습니다.

**Comment by B-G-Y** [comment]
좀 더 보완해서 업로드하겠습니다.

아이디어 내주셔서 감사합니다.

**Comment by B-G-Y** [comment]
d30f9e47479cd0767f619aeb450cd9941650edad

말씀해주신 것처럼

일간 인기차트뿐만 아니라 

실시간(24H) 인기차트, 주간 인기차트 기능을 구현하였습니다. 

확인부탁드립니다.

**Comment by B-G-Y** [comment]
d30f9e47479cd0767f619aeb450cd9941650edad
처럼 실시간, 주간, 인기차트 기능을 추가하였으나 

기능을 구현하면서 코드가 너무 길어져

825dbb0935833f92215a9dad119274032a72894e

1위 ~ 5위에서 1위 ~ 3위로 출력하게 만들었습니다.

확인부탁드립니다.

**Comment by DaeguKIng** [comment]
해당 기능에 대한 실행을 잘 확인하였습니다. 의견 수렴에 대한 감사를 전합니다.
