### ISSUE TITLE
Covid_cardlist.py 실행에 대하여

### ISSUE THREAD

**Issue by B-G-Y** [B-G-Y/Team_Project_OPSW#9]
3ee6d29ae8e7e7658539512de54b37c948b629bd

의 파일인 Covid_cardlist.py를 실행할때 가끔 채널 봇이 응답을 안할 때가 있습니다.

![66](https://user-images.githubusercontent.com/76954598/119094424-f921fd80-ba4b-11eb-9e87-7039c1d1a09e.png)

위 사진과 같이 

'발생동향'에서만 응답이 안오는 경우가 있습니다.

이에 대하여 수정부탁드립니다.

수정후 확인받고 origin:master에 merge하면 될것같습니다.

**Comment by DaeguKIng** [comment]
지적 감사합니다. 빠른 시일 내 버그 수정 후 확인 및 master branch에 merge하도록 하겠습니다.

**Comment by DaeguKIng** [comment]
수정후 Feature/KDY에 push해두었습니다. 확인 부탁드립니다.

**Comment by B-G-Y** [comment]
네 확인했습니다. 정상대로 실행됩니다.
